// <auto-generated />
using System;
using ExpertsClub.Teste.EntityFramework.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExpertsClub.Teste.EntityFramework.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210824185109_AdicionarCategoria")]
    partial class AdicionarCategoria
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ExpertsClub.Teste.EntityFramework.Model.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.HasKey("Id");

                    b.ToTable("Categoria");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fe0f2703-8d1f-4723-b234-e2c7c85f1dd4"),
                            Nome = "Papelaria"
                        },
                        new
                        {
                            Id = new Guid("d20ad953-5441-4675-8ddd-25ddcf3da593"),
                            Nome = "Informática"
                        });
                });

            modelBuilder.Entity("ExpertsClub.Teste.EntityFramework.Model.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Produto");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dda07aab-a5c7-429d-99c7-7d52943c1e8a"),
                            CategoriaId = new Guid("fe0f2703-8d1f-4723-b234-e2c7c85f1dd4"),
                            Nome = "Caneta Bic",
                            Valor = 1m
                        },
                        new
                        {
                            Id = new Guid("ec8987c0-ce4f-4006-a540-e1d6c40a3b1c"),
                            CategoriaId = new Guid("fe0f2703-8d1f-4723-b234-e2c7c85f1dd4"),
                            Nome = "Caneta Azul",
                            Valor = 1.39m
                        },
                        new
                        {
                            Id = new Guid("aa3d9ff8-d320-4feb-a0a6-12dc42885d1a"),
                            CategoriaId = new Guid("fe0f2703-8d1f-4723-b234-e2c7c85f1dd4"),
                            Nome = "Caneta Vermelha",
                            Valor = 1.40m
                        },
                        new
                        {
                            Id = new Guid("a72859e3-9865-4833-bfc3-29e41bd443f9"),
                            CategoriaId = new Guid("fe0f2703-8d1f-4723-b234-e2c7c85f1dd4"),
                            Nome = "Caneta Preta",
                            Valor = 1.41m
                        },
                        new
                        {
                            Id = new Guid("fb2273a5-42f2-4a12-af7b-aca91121a4b1"),
                            CategoriaId = new Guid("fe0f2703-8d1f-4723-b234-e2c7c85f1dd4"),
                            Nome = "Lápis",
                            Valor = 0.37m
                        },
                        new
                        {
                            Id = new Guid("e0454b5c-f584-4aad-9570-a5f4760441a3"),
                            CategoriaId = new Guid("fe0f2703-8d1f-4723-b234-e2c7c85f1dd4"),
                            Nome = "Borracha",
                            Valor = 0.74m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
