// <auto-generated />
using System;
using ExpertsClub.Teste.EntityFramework.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExpertsClub.Teste.EntityFramework.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210824191659_AdicionarProdutosInformatica")]
    partial class AdicionarProdutosInformatica
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ExpertsClub.Teste.EntityFramework.Model.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.HasKey("Id");

                    b.ToTable("Categoria");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fe0f2703-8d1f-4723-b234-e2c7c85f1dd4"),
                            Nome = "Papelaria"
                        },
                        new
                        {
                            Id = new Guid("d20ad953-5441-4675-8ddd-25ddcf3da593"),
                            Nome = "Informática"
                        });
                });

            modelBuilder.Entity("ExpertsClub.Teste.EntityFramework.Model.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Produto");

                    b.HasData(
                        new
                        {
                            Id = new Guid("70e42eaa-a65a-4597-9dea-69df16d2af47"),
                            CategoriaId = new Guid("fe0f2703-8d1f-4723-b234-e2c7c85f1dd4"),
                            Nome = "Caneta Bic",
                            Valor = 1m
                        },
                        new
                        {
                            Id = new Guid("df60ef32-7006-4642-97a2-dd243c04c3ef"),
                            CategoriaId = new Guid("fe0f2703-8d1f-4723-b234-e2c7c85f1dd4"),
                            Nome = "Caneta Azul",
                            Valor = 1.39m
                        },
                        new
                        {
                            Id = new Guid("db3cd00d-638b-4170-8835-2ab68d770928"),
                            CategoriaId = new Guid("fe0f2703-8d1f-4723-b234-e2c7c85f1dd4"),
                            Nome = "Caneta Vermelha",
                            Valor = 1.40m
                        },
                        new
                        {
                            Id = new Guid("4f6dbedb-ea4a-49f8-8324-b1edb53b172d"),
                            CategoriaId = new Guid("fe0f2703-8d1f-4723-b234-e2c7c85f1dd4"),
                            Nome = "Caneta Preta",
                            Valor = 1.41m
                        },
                        new
                        {
                            Id = new Guid("d11b2c36-2826-4b7c-b4da-bd7f78047982"),
                            CategoriaId = new Guid("fe0f2703-8d1f-4723-b234-e2c7c85f1dd4"),
                            Nome = "Lápis",
                            Valor = 0.37m
                        },
                        new
                        {
                            Id = new Guid("f22a1d61-5148-4dd8-ae83-c52bd500cc86"),
                            CategoriaId = new Guid("fe0f2703-8d1f-4723-b234-e2c7c85f1dd4"),
                            Nome = "Borracha",
                            Valor = 0.74m
                        },
                        new
                        {
                            Id = new Guid("0a3242c2-ca91-4f5c-9d36-fae235bf1c18"),
                            CategoriaId = new Guid("d20ad953-5441-4675-8ddd-25ddcf3da593"),
                            Nome = "Pendrive",
                            Valor = 27.90m
                        },
                        new
                        {
                            Id = new Guid("c15b3d4d-1de7-4145-8900-69bbce833188"),
                            CategoriaId = new Guid("d20ad953-5441-4675-8ddd-25ddcf3da593"),
                            Nome = "Mouse",
                            Valor = 33.50m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
